### ISSUE TITLE
HD-6000 too

### ISSUE THREAD

**Issue by legolas-a20** [anotherlab/FocusUF#3]
Hi, the MS Lifecam HD-6000 has the same issue.  It is fully named "Microsoft® LifeCam HD-6000 for Notebooks", so maybe it would be nice to change
d.Name == "Microsoft® LifeCam HD-5000"
to something like 
d => d.Name.StartsWith("Microsoft® LifeCam HD-"
Or just explicitly test for both?

**Comment by anotherlab** [comment]
Fixed with @cainhopwood's PR
